### ISSUE TITLE
Android - Could not find com.google.ai.client.generativeai:generativeai:0.2.2.

### ISSUE THREAD

**Issue by yusuf0x** [google-gemini/generative-ai-android#102]
I'm attempting to use the generativeai library version 0.2.2 in my project .  but i get this error _Could not find com.google.ai.client.generativeai:generativeai:0.2.2._

**Comment by rlazo** [comment]
Hey @yusuf0x the library is available in Google's maven repository

https://maven.google.com/web/index.html?q=generati#com.google.ai.client.generativeai:generativeai:0.2.2

Maybe your project is missing the `google()` repository in the `settings.gradle.kts` file?

**Comment by yusuf0x** [comment]
Thanks for you response but still the same after adding ` google()`
![test1](https://github.com/google/generative-ai-android/assets/102838098/2d5d21f4-0e99-4a58-8fc1-6b1a50156d1c)

i get this error 
![test](https://github.com/google/generative-ai-android/assets/102838098/35ba226c-1af1-4dab-a03a-ca947dac7efc)

**Comment by yusuf0x** [comment]
Hey @rlazo  
I get the same error after adding `google()`
i don't know what is the problem ?

**Comment by rlazo** [comment]
Could you share the output of gradle? It usually lists where it looked for the artifacts and that maybe gives us a clue why it's not working.

**Comment by yusuf0x** [comment]
Here is the output of gradle 

```
project_android:test: Could not resolve com.google.ai.client.generativeai:generativeai:0.2.2.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```
build.gradle.kst 
```
repositories {
  mavenCentral()
  google()

}

```
settings.gradle 

```
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
       google()
    }
}

```

**Comment by rlazo** [comment]
Hey @yusuf0x your `settings.gradle` file should look similar to this

```
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
```

You need `google()` in both `pluginManagement` and `dependencyResolutionManagement`

**Comment by popkter** [comment]
@yusuf0x Hello，how do u fix this error ? i got the same error in my compose for desktop project.

my build.gradle.kts
```kotlin
import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    kotlin("jvm")
    id("org.jetbrains.compose")
}

group = "com.pop.composedemo"
version = "1.0-SNAPSHOT"

repositories {
    google()
    mavenCentral()
    gradlePluginPortal()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
}

dependencies {
    implementation(compose.desktop.currentOs)

    implementation(libs.gson)
    implementation(libs.generativeai)

}

compose.desktop {
    application {
        mainClass = "MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "demo"
            packageVersion = "1.0.0"
        }
    }
}

```
and my settings.gradle.kts
```kotlin
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    }

    plugins {
        kotlin("jvm").version(extra["kotlin.version"] as String)
        id("org.jetbrains.compose").version(extra["compose.version"] as String)
    }
}


rootProject.name = "demo"
```

**Comment by rlazo** [comment]
Hi @popkter this library is an android library, so it probably doesn't work on desktop

**Comment by popkter** [comment]
> Hi @popkter this library is an android library, so it probably doesn't work on desktop

GOT，thank u
