### ISSUE TITLE
Error in accessing gemini-1.5-pro-latest

### ISSUE THREAD

**Issue by hassanabidpk** [google-gemini/generative-ai-android#105]
Is `gemini-1.5-pro-latest` model available in Android SDK ?
Getting following error 
`API Error: models/gemini-1.5-pro-latest is not found for API version v1, or is not supported for GenerateContent. Call ListModels to see the list of available models and their supported methods.`

**Comment by rlazo** [comment]
Hey @hassanabidpk `gemini-1.5` is still in limit preview, so it's not accessible broadly.

**Comment by thatfiredev** [comment]
@hassanabidpk Gemini 1.5 Pro has [opened for Public Preview today](https://developers.googleblog.com/2024/04/gemini-15-pro-in-public-preview-with-new-features.html). :)

You can now use it in the Android SDK by specifying the "v1beta" `apiVersion`:

```kotlin
val generativeModel = GenerativeModel(
  modelName = "gemini-1.5-pro-latest",
  apiKey = BuildConfig.apiKey
  requestOptions = RequestOptions(apiVersion = "v1beta")
)
```

**Comment by bpavuk** [comment]
that must be documented in the FAQ, I think

**Comment by jochenkirstaetter** [comment]
You need to use API version v1beta instead of v1.

**Comment by rlazo** [comment]
Hey folks. We've decided to move to use api version "v1beta" by default, which will prevent this issue. See https://github.com/google-gemini/generative-ai-android/pull/123 for the code changes. I'll update this issue once more when the new version is released.

Thanks everyone!

**Comment by rlazo** [comment]
The release is out! Now, since it defaults to v1beta, using 1.5 shouldn't require any additional configuration. Thanks everybody
