### ISSUE TITLE
Something went wrong while trying to deserialize a response from the server (2)

### ISSUE THREAD

**Issue by Tolansoft** [google-gemini/generative-ai-android#139]
Hello, we solved the problem mentioned in #17  by adding the relevant line to the proguard file, but it does not work in any version after v.0.2.0. We continue to receive the same error in the release version. I tried all versions one by one and tested it on the internal channel, only v0.2.0 works.

**Comment by AmitJayant** [comment]
0.2.2 also works.
But above that all fails in production with proguard.

**Comment by rlazo** [comment]
Hi @Tolansoft PR #141 should address the issue. We will keep this issue open until we release a new version of the SDK that includes the fix.

**Comment by Tolansoft** [comment]
Thank you!

7 May 2024 Sal 05:45 tarihinde Rodrigo Lazo ***@***.***> şunu
yazdı:

**Comment by rlazo** [comment]
Thanks for your patience folks! v0.6.0 is out and contains the fix for this issue

https://github.com/google-gemini/generative-ai-android/releases/tag/v0.6.0
