### ISSUE TITLE
Get api key

### ISSUE THREAD

**Issue by ahmedaa6122** [google-gemini/generative-ai-android#140]
How i can get api key from user account like using auth2 or Google signin library to get api key without get it from website ate there any library for android kotlin?. Thankd

**Comment by singhniraj08** [comment]
@ahmedaa6122, You can follow feedback [Get started with the Gemini API in Android apps (client SDK)](https://ai.google.dev/gemini-api/docs/get-started/android) tutorial to access the Gemini API directly from your Android app using the Google AI client SDK for Android. Kindly let us know if this answers your query. Thank you!

**Comment by ahmedaa6122** [comment]
@singhniraj08 
It's not help me for any thing about get api key from thired party library or http request .any help please?

**Comment by rlazo** [comment]
Hi @ahmedaa6122 the API key is tied to a project, and not to a user, so you can't use auth libraries to get the key. As @singhniraj08 commented, the tutorial describes how to get an API key for your app.
