### ISSUE TITLE
Gemini 1.5 Pro Error: "Something went wrong while trying to deserialize a response from the server."

### ISSUE THREAD

**Issue by karloti** [google-gemini/generative-ai-android#160]
### Description of the bug:

I get this **error** very, very often. I wait about **15 seconds** and repeat the **prompt** until I get a normal response. The prompt is not in English. This wastes a lot of time and I don't know how to fix it. Is there a way to handle errors? The model returns them to normal text that I have to parse. So far I have received over x3 types of different errors from Gemini 1.5 Pro.

![image](https://github.com/google-gemini/generative-ai-android/assets/6735500/4b55dd2a-4ad1-48d2-b14d-13712f8328aa)

**Comment by karloti** [comment]
### BILLING from google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent
Gemini requests are currently being billed to me. The problem is that I get an error from the library and no result.
Please tell me what to do? This library has a serialization error. I repeatedly repeat the request until I get an answer that does not have an error and in this way insanely large amounts are charged. Is there a way to not charge these errors? If not, in this case this library is not appropriate to use because it generates billing that is without any content.
For example, here is the following error:

![image](https://github.com/google-gemini/generative-ai-android/assets/6735500/b2c91632-bf74-4fd7-9793-f493d0500331)

**Comment by rlazo** [comment]
Hey @karloti could you share the prompt you are using that's triggering the deserialization issue for debugging?

**Comment by karloti** [comment]
Hello,
thanks for your quick reply.
I think this is where the problem comes from. I'm thinking of replacing it with a String scheme

![image](https://github.com/google-gemini/generative-ai-android/assets/6735500/b3aa77bb-41ad-4cda-98ab-367ddf83baf1)

**Comment by davidmotson** [comment]
I think the issue may be because you are subclassing FunctionDeclaration. This is not the intended use. Does this error also occur if you use the defineFunction methods?

**Comment by rlazo** [comment]
Sounds like a possibility, since the trace points to that line 

```
	at com.google.ai.client.generativeai.common.shared.FunctionCall$$serializer.deserialize(Types.kt:62)
```

that being said, it should absolutely not fail deserializing. The model is not returning a value that we were expecting.

**Comment by davidmotson** [comment]
relatedly, if you happen to be able to pull the text of one of these responses that fails to parse that would help debugging immensely. If you're in android studio you can use the network inspector in App Inspection to accomplish this.

**Comment by karloti** [comment]
> relatedly, if you happen to be able to pull the text of one of these responses that fails to parse that would help debugging immensely. If you're in android studio you can use the network inspector in App Inspection to accomplish this.

I can give you the prompt, but I don't want it here publicly. Maybe an email. Note that the prompt is in Bulgarian and this may be a problem. However, the fact is that the same prompt has no problem in AI Studio

**Comment by davidmotson** [comment]
Actually, the response is more important, Feel free to remove any strings you like from it, the structure is whats important.

If you'd prefer to email it to me, you can email it to davidmotson@google.com

**Comment by rlazo** [comment]
Alternatively, you could record request/responses send to the server using https://developer.android.com/studio/debug/network-profiler

That would allow us to see what gets send and what you get back. As @davidmotson said, structure matters rather than content, so you can edit out the values.

**Comment by karloti** [comment]
I suspect that the error is caused by the serialization of the returned list of candidates.

![image](https://github.com/google-gemini/generative-ai-android/assets/6735500/25c00b44-9f0d-407d-8b65-94c726357180)
![image](https://github.com/google-gemini/generative-ai-android/assets/6735500/54c917db-8eca-40e3-9d88-7676cafa58ee)

**Comment by karloti** [comment]
> Alternatively, you could record request/responses send to the server using https://developer.android.com/studio/debug/network-profiler
> 
> That would allow us to see what gets send and what you get back. As @davidmotson said, structure matters rather than content, so you can edit out the values.

### I have used **null safe text** for TextPart(val text: String)

![image](https://github.com/google-gemini/generative-ai-android/assets/6735500/6c27b9e6-f26a-4298-9374-78ed29fc6bf2)

**Comment by karloti** [comment]
This bug will be fixed in **version v0.8.0**
I have already tested the latest update and the bug is caught. 
Thanks to David for fixing this.

**Comment by karloti** [comment]
![image](https://github.com/google-gemini/generative-ai-android/assets/6735500/295556db-e2f5-4527-8ab5-ebc1f89e7417)
![image](https://github.com/google-gemini/generative-ai-android/assets/6735500/d8db45bb-4fa8-481c-803b-bc2caccbafb8)
![image](https://github.com/google-gemini/generative-ai-android/assets/6735500/9a158ac1-d9b4-49fe-8606-381b843adde9)
![image](https://github.com/google-gemini/generative-ai-android/assets/6735500/397233ce-08a5-40be-989d-236d1f70b914)

**Comment by rlazo** [comment]
> ![image](https://private-user-images.githubusercontent.com/6735500/337888833-295556db-e2f5-4527-8ab5-ebc1f89e7417.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTg4MzcsIm5iZiI6MTcxODE1ODUzNywicGF0aCI6Ii82NzM1NTAwLzMzNzg4ODgzMy0yOTU1NTZkYi1lMmY1LTQ1MjctOGFiNS1lYmMxZjg5ZTc0MTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMDIxNTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTYwZDZhZmM0ZTE3MDdjNDg5MTU3MzcyMTkyMjc4ZGI1OTk1MmU1MDE1ZTE5MWUxOTM4NGZhYzMyY2I5MDIzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RrdRdpOAPHDrTz_a_cHBZIGGIQqtfIeJZbXa8cQ26p8) ![image](https://private-user-images.githubusercontent.com/6735500/337889258-d8db45bb-4fa8-481c-803b-bc2caccbafb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTg4MzcsIm5iZiI6MTcxODE1ODUzNywicGF0aCI6Ii82NzM1NTAwLzMzNzg4OTI1OC1kOGRiNDViYi00ZmE4LTQ4MWMtODAzYi1iYzJjYWNjYmFmYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMDIxNTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWYyZDJlZjMyNzBjMjdiOGY0M2VjZThlYjIyNjc5M2RlMDQ2ZWI3ZjU4OGYwYTYwZDNhMmM3ODgzZjNjZGJiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._DzIiRe66fJfsWlLZDPgsWxw81WvPe0FM2I_q8YW-M8) ![image](https://private-user-images.githubusercontent.com/6735500/337889588-9a158ac1-d9b4-49fe-8606-381b843adde9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTg4MzcsIm5iZiI6MTcxODE1ODUzNywicGF0aCI6Ii82NzM1NTAwLzMzNzg4OTU4OC05YTE1OGFjMS1kOWI0LTQ5ZmUtODYwNi0zODFiODQzYWRkZTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMDIxNTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2VlYzFkYmQ1NTAwMmY2OTAxOWEyNTYxODIwMDI2NTNjYjFkZWUwZWMyNmZhOGE0YjE1MjM1NmE0MTMyYTEzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bXPmiraZh3fZfGoXb2qTMBnt7xvD5ioEfvhP_zIZt7U) ![image](https://private-user-images.githubusercontent.com/6735500/337889872-397233ce-08a5-40be-989d-236d1f70b914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTg4MzcsIm5iZiI6MTcxODE1ODUzNywicGF0aCI6Ii82NzM1NTAwLzMzNzg4OTg3Mi0zOTcyMzNjZS0wOGE1LTQwYmUtOTg5ZC0yMzZkMWY3MGI5MTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMDIxNTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWNjYzU5NDNkNmI1ZjFmOWFlMmExMTFjZTMwODhjMmZlNjcxNTNhY2ViNDBmOWIyMDVjZGIzNDcyOWM0ZjU3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CAopfxZEKTvhywday7tm3Pcvgohnx2SpdBDzo946Nss)
> 
> @davidmotson https://drive.google.com/drive/folders/10S8eA3nXlkxUjqlK9EuIptzDMF7WQJf1?usp=sharing

Seems like this is not the same issue as the original one. Please create a new issue to track it separately. Thanks!
