### ISSUE TITLE
Recitation Error

### ISSUE THREAD

**Issue by chaoticcoder1507** [google-gemini/generative-ai-android#167]
### Description of the bug:

Whenever I am asking for a general code its giving me error.

### Actual vs expected behavior:

Actually it should give me code

**Comment by singhniraj08** [comment]
@chaoticcoder1507, Thank you reporting this issue. 
This repository is for issues related to Android SDK client bugs or improvements and the client doesn't control the service's responses. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Discourse forum](https://discuss.ai.google.dev/).

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)
