### ISSUE TITLE
FunctionDeclaration with optional function

### ISSUE THREAD

**Issue by paulotaylor** [google-gemini/generative-ai-android#169]
### Description of the feature request:

Currently the FunctionDeclaration requires a function suspend parameter. Would it be possible to declare a FunctionDeclaration instance with the function as optional?

### What problem are you trying to solve with this feature?

In my use case, when a specific function is called, it doesn't fetch the data immediately, it actually requires user input and only after gathering the data from the users' input it sends the parameters back to gemini. I found this incompatibility when I was porting the vertex-ai implementation to the generative-ai-android library. I'll keep using the vertext-ai implementation for now

**Comment by rlazo** [comment]
Hi @paulotaylor we are working on making changes to the code so passing the function isn't needed. I'll update this issue when we have the actual proposal out. Thanks!

**Comment by rlazo** [comment]
Hi @paulotaylor since version 0.9.0 this should be possible. Give it a try and let us know if you find any issues. Thanks!
