### ISSUE TITLE
Sudden constant Error code 500 (Internal Error) with the Gemini API in my Android app 

### ISSUE THREAD

**Issue by theJayTea** [google-gemini/generative-ai-android#209]
### Description of the bug:

Hello! Today, I've suddenly been having this error constantly, across Google Accounts and API keys when using the Gemini API through my Android app. **It was working perfectly fine the last few days.**
I'm using the free API, and I was planning to pay for it but I'm having second thoughts now.

```
Error: Unexpected Response:

"error": {
"code": 500,
"message": "An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting",
"status": "INTERNAL"

kotlinx. serialization. MissingFieldException: Field 'details' is required for type with serial name 'com.google.ai.client.generativeai.common.server. GRpcError', but it was missing at path: $.error
```

The following is my model initialisation code. Is it because I'm doing something wrong here?

```
        Content systemInstructionsContent = new Content.Builder()
                .addText(systemInstructions)
                .build();


        GenerativeModel gm = new GenerativeModel(
                "gemini-1.5-pro",
                apiKey,
                null,
                null,
                new RequestOptions(), // Use default RequestOptions
                null,
                null,
                systemInstructionsContent
        );
```

I'm leaving some of the parameters as null, as I want them at the default and only want to add a system prompt.
I'm using Java to call the model from my Android app!

Thanks so so much for the help!

### Actual vs expected behavior:

Expected behaviour: API calls work, without randomly sometimes returning Error code 500

Actual behaviour: For the last day, requests have been constantly returning error code 500 almost all the time

**Comment by erendogan6** [comment]
I started getting this error today as well.

**Comment by kouexo** [comment]
I'm experiencing this while using Python. I started getting the same error today. I'm using the same code that was working normally two weeks ago. Occasionally, the API request succeeds, but most of the time it results in a 500 error code.
![image](https://github.com/user-attachments/assets/7658d7cb-9a26-450d-9d67-a1bd7b91330e)

**Comment by KawshikManikantan** [comment]
Same error noted. How can this be resolved?

**Comment by singhniraj08** [comment]
@theJayTea,
Thank you reporting this issue. This looks like an intermittent error and should work now. 
This repository is for issues related to Android SDK client bugs or improvements and the client doesn't control the service's responses. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Google AI forum](https://discuss.ai.google.dev/).

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)
